#!/bin/bash
# Setup script for SMTP environment variables
# Run this script to set up your email configuration

echo "Setting up SMTP configuration for automatic email sending..."
echo ""

# Prompt for SMTP settings
read -p "SMTP Host (default: smtp.gmail.com): " smtp_host
smtp_host=${smtp_host:-smtp.gmail.com}

read -p "SMTP Port (default: 587): " smtp_port
smtp_port=${smtp_port:-587}

read -p "SMTP User (your email): " smtp_user

read -sp "SMTP Password (or App Password for Gmail): " smtp_password
echo ""

read -p "From Email (default: same as SMTP_USER): " smtp_from_email
smtp_from_email=${smtp_from_email:-$smtp_user}

read -p "From Name (default: Build-a-Dress Team): " smtp_from_name
smtp_from_name=${smtp_from_name:-Build-a-Dress Team}

read -p "Use TLS? (default: true): " smtp_use_tls
smtp_use_tls=${smtp_use_tls:-true}

# Create .env file
cat > .env << EOF
# SMTP Configuration for Automatic Email Sending
# Generated by setup_env.sh

SMTP_HOST=$smtp_host
SMTP_PORT=$smtp_port
SMTP_USE_TLS=$smtp_use_tls
SMTP_USER=$smtp_user
SMTP_PASSWORD=$smtp_password
SMTP_FROM_EMAIL=$smtp_from_email
SMTP_FROM_NAME=$smtp_from_name
EOF

echo ""
echo "✓ .env file created successfully!"
echo ""
echo "To use these settings, run:"
echo "  source .env"
echo ""
echo "Or add this to your shell profile (.zshrc, .bashrc, etc.) to load automatically:"
echo "  source $(pwd)/.env"

